[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "LIME_Stratified"
authors = [{name = "Rashid", email = "muhammadrashid8045@gmail.com"}]
dynamic = ["version", "description"]
